spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ehrbase
    username: ehrbase_restricted
    password: ehrbase_restricted
    hikari:
      maximum-pool-size: 50
      max-lifetime: 1800000
      minimum-idle: 10
  flyway:
    schemas: ehr
    user: ehrbase
    password: ehrbase

security:
  authType: NONE


